### ISSUE TITLE
Is this the vrep dockerhub image pointing to this repo?

### ISSUE THREAD

**Issue by ags-dy** [gvgramazio/docker-vrep#1]
Is the image in:
https://hub.docker.com/r/gramaziokohler/vrep
pointing to this github repo?  They seem to have different behaviour, where the dockerhub image automatically loads vrep whereas this one does not.

Do you have a link to the Dockerfile for the dockerhub image?

Thanks

**Comment by gvgramazio** [comment]
@ags-dy No, it doesn't point to this repo and I don't know where it points to. My username on dockerhub isn't `gramaziokohler` but `gvgramazio`. I don't know who he/she is so I cannot give any information about that docker image. However, if you want, you can use the corresponding image of this repo on dockerhub, it's [gvgramazio/vrep](https://hub.docker.com/r/gvgramazio/vrep). I wrote it some time ago so it may have some issues and since it was only for personal use it doesn't have any documentation. If you'll decide to give it a try and encounter some problems feel free to report here or to make a pull request.

**Comment by ags-dy** [comment]
Ok, thanks.  I updated your code to work with the latest vrep release 3.6.1 rev4

```
 
FROM ubuntu:16.04

LABEL mantainer="gvgramazio@gmail.com" \
      version="0.1"

RUN apt-get update && apt-get install -y \
  wget \
  libglib2.0-0  \
  libgl1-mesa-glx \
  xcb \
  "^libxcb.*" \
  libx11-xcb-dev \
  libglu1-mesa-dev \
  libxrender-dev \
  libxi6 \
  libdbus-1-3 \
  libfontconfig1 \
  xvfb \
  libqt5x11extras5 \
  xz-utils \
  && rm -rf /var/lib/apt/lists/*

RUN wget http://coppeliarobotics.com/files/V-REP_PRO_EDU_V3_6_1_Ubuntu16_04.tar.xz
RUN tar -xf V-REP_PRO_EDU_V3_6_1_Ubuntu16_04.tar.xz
RUN apt-get remove -y wget

RUN echo 'export QT_DEBUG_PLUGINS=1' >> ~/.bashrc
RUN echo 'export PATH=/V-REP_PRO_EDU_V3_6_1_Ubuntu16_04/:$PATH' >> ~/.bashrc

```

**Comment by gvgramazio** [comment]
@ags-dy Feel free to fork my repo or to actively contribute on this one by sending a pull request with your changes, it will automatically update the image on docker hub when accepted.
